---

- name: restart firewalld
  become: yes
  service:
    name: firewalld
    enabled: yes
    state: restarted

- name: restart postfix
  systemd:
    name: postfix
    daemon_reload: true
    enabled: true
    state: started

- name: restart sshd
  debug:
    msg: "checking /etc/ssh/sshd_config first"
  changed_when: true
  notify:
    - check sshd configuration

- name: check sshd configuration
  command: '/usr/sbin/sshd -t'
  register: sshd_config
  changed_when: "sshd_config.rc != 0"
